### ISSUE TITLE
Mqtt port !!!!

### ISSUE THREAD

**Issue by arpagor62970** [project-alice-assistant/HermesLedControl#101]
**The bug**
in line 46 of /home/pi/hermesLedControl_v2.0.13/models/engines/rhasspy.py
we have : 
46                          configs['mqttPort'] = conf['mqtt'].get('port', 12183)
The port is constantly set and poses a problem for users who have changed it !!!
the modification to be made is:
46                          configs['mqttPort'] = conf['mqtt'].get('port', '')

Bye
Arpagor

**Comment by Psychokiller1888** [comment]
.get(foo, bar) tries to get foo from the list and returns bar if the key is not found...
