### ISSUE TITLE
Arguments to the install script (like `--help`) seem to get stuck in the install path somehow

### ISSUE THREAD

**Issue by fake-name** [project-alice-assistant/HermesLedControl#105]
Basically, I tried to install:

```
pi@raspberrypi:~/HermesLedControl-2.0.14$ sudo ./install --help
sudo: ./install: command not found
1 pi@raspberrypi:~/HermesLedControl-2.0.14$ sudo ./install.sh --help
<answered questions>
```

As a result, somehow I seem to now have a (broken) venv at `/home/pi/hermesLedControl_--help/venv/bin/python3 main.py`. 

The function of args passed to the install script don't seem to be documented anywhere, and looking in `/home/pi/hermesLedControl_--help` it's missing `main.py`, so I suspect that the space/dashes are breaking some part of the install process. I went on with installing things after trying --help assuming it was just ignored, not being used as a venv suffix?

**Comment by Psychokiller1888** [comment]
I never answered that one, and I'm sorry for that. There's no args for install.sh
