### ISSUE TITLE
HermesLedControl install on RPi zero failed

### ISSUE THREAD

**Issue by romakrau** [project-alice-assistant/HermesLedControl#124]
**Do not remove fields, answer them, otherwise your bug will be reported as invalid and closed**

**How I did start SLC, with what arguments**
I try to install hlc on a RPi zero using the hlc_download script.

**ReSpeaker 2**

**The bug**
The install script add a wrong directory to the service file. There is no main.py script in venv directory. The py scripts are all in hermesLedControl_v3.0.4 and not excecutive. 
-rw-rw-r--  1 pi root  1404 Jul 16  2022 main.py
Changing this didn't help. HermesLedControl won't start.

**Debug output**
Jan 20 16:18:58 raspberrypi systemd[1]: Started Hermes Led Control.
Jan 20 16:18:58 raspberrypi python[938]: /home/pi/HermesLedControl/venv/bin/python: can't open file '/home/pi/HermesLedControl/main.py': [Errno 2] No such file or directory
Jan 20 16:18:58 raspberrypi systemd[1]: hermesledcontrol.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 20 16:18:58 raspberrypi systemd[1]: hermesledcontrol.service: Failed with result 'exit-code'.

**To Reproduce**
several times

Maybe could you be so kind and check the install script or give me any other hint.
Thanks Roman

**Comment by Psychokiller1888** [comment]
Hi! Sorry for the late answer!

The issue is that it installed in "hermesLedControl_v3.0.4" instead of "HermesLedControl". Just rename that directory. I'll check the installer
