### ISSUE TITLE
Support for Jabra Speak 410 (USB)

### ISSUE THREAD

**Issue by federico2015** [project-alice-assistant/HermesLedControl#57]
Thank for your work, is it possible to control this device?

**Comment by Psychokiller1888** [comment]
? There's no led on that device

**Comment by federico2015** [comment]
There are 12 LEDs, 1 LED (just over Jabra Logo) stay always white and I'd to use it for HotWord found feedback, when you switch mute ON all LEDs stay red.
There are also some buttons: Mute On/Off, Vol. +, Vol. -, Green Phone (answer), Red Phone (End Call), Jabra logo and Tringle (custom use).
![IMG_2555](https://user-images.githubusercontent.com/56437058/66654679-13beae80-ec3b-11e9-9199-52e02c015c15.jpeg)
![IMG_2556](https://user-images.githubusercontent.com/56437058/66654683-14efdb80-ec3b-11e9-8b71-f052201cdcf3.jpeg)
I know that Jabra has SDK for connecting to it.
Hope this can help, thank you.
