### ISSUE TITLE
Add timeout option

### ISSUE THREAD

**Issue by Xenira** [project-alice-assistant/HermesLedControl#86]
**Is your feature request related to a problem? Please describe.**
Sometimes the current animation gets stuck (not a problem of this project but with my rhasspy instance not sending the proper message / needing to be restarted etc.) on an animation. I would like to define a timeout after which the leds are switched off.

**Describe the solution you'd like**
There should be an argument (maybe --timeout) which accepts a time in seconds after which idle or stop is called (not sure which one is correct..
Any state change resets this timer.

**Describe alternatives you've considered**
I have considered adding a mqtt listener to send the required event should there be a missing deactivation. But integrating this here would be cleaner and more convenient.

**Additional context**
Seems to be sometimes related to #63.

**Comment by Xenira** [comment]
I can implement the issues submitted by me. But I wanted your feedback first.

**Comment by Psychokiller1888** [comment]
Hey, thanks for your input! Sure, I like the idea! Do not hesitate to clean up stuff, it's been a serious while I haven't touch HLC and it would need a serious refactoring.

**Comment by Xenira** [comment]
Would idle or stop be correct? Ive seen that most patterns call stop inside idle.

**Comment by Psychokiller1888** [comment]
Idle would call the idle animation, so that would be correct. If the idle animation is empty, then it stops
