### ISSUE TITLE
Add option for DoA to setup for supported devices

### ISSUE THREAD

**Issue by Xenira** [project-alice-assistant/HermesLedControl#88]
**Is your feature request related to a problem? Please describe.**
DoA needs numpy and libatlas-base-dev. Also --enableDoA needs to be set to true.

**Describe the solution you'd like**
When selecting supported hardware during setup the user should be asked if DoA should be enabled.
If yes numpy and libatlas-base-dev should be installed an --enableDoA should be set to true.

**Describe alternatives you've considered**
None

**Additional context**
Also add a wiki article about this for manual setup.

**Comment by Psychokiller1888** [comment]
Yep, haven't finished that one tbh, I totally fogot about it.... But I think it was working, must have forgotten to add the required packages.
