### ISSUE TITLE
Led stripes?  how connect whit GPIO?

### ISSUE THREAD

**Issue by dwarfwalker** [project-alice-assistant/HermesLedControl#92]
Hello, im new to raspberry, can I use 2 led stripes (chinese) whit hermers led control?
How i can connect it to gpio?
I have built a magic mirror, whit:
-  homeassistant,
-  rhasspy
-  nodered 
-  mqtt server 
I want the two side of the mirror whit led stripes, whit animation looks likes Alexa.
Thanks

**Comment by Xenira** [comment]
Could you give some details about the led stripe?
Which chipset does it use? One or two data lines?
Do you want to connect the led stripe directly to the Pi or do you want to use something like a nodemcu? If so you might want to have a look at https://esphome.io/components/light/fastled.html

Please keep in mind, that the stripes might need an additional power supply.

I could imagine that something linke fastled (or python equivalent) could be used to address the led strip.
I might look into that.

Also, please stick to the issue templates.

**Comment by dwarfwalker** [comment]
> Could you give some details about the led stripe?
> Which chipset does it use? One or two data lines?
> Do you want to connect the led stripe directly to the Pi or do you want to use something like a nodemcu? If so you might want to have a look at https://esphome.io/components/light/fastled.html
> 
> Please keep in mind, that the stripes might need an additional power supply.
> 
> I could imagine that something linke fastled (or python equivalent) could be used to address the led strip.
> I might look into that.
> 
> Also, please stick to the issue templates.

The led strips are 2, only 1 color, so whit only + and - connect cable, i found another magic mirror project where the led strip are connected whit Power supply and a mosfet irfz44n to Raspberry gpio likes this:
![1612513543222](https://user-images.githubusercontent.com/77108056/107008588-3d86d780-6794-11eb-9b15-e6a62bd33350.jpg)
Can It work whit HermesLedControl?
Thx

**Comment by Psychokiller1888** [comment]
You connect to the gpio of your choice and select the option "gpio leds" in the installer
