### ISSUE TITLE
sed: can’t read /home/pi/.config/hermesLedControl/configuration.yml from install script

### ISSUE THREAD

**Issue by jazzy-r** [project-alice-assistant/HermesLedControl#93]
**Do not remove fields, answer them, otherwise your bug will be reported as invalid and closed**

**How I did start SLC, with what arguments**
Via the hlc_download.sh script using sudo permissions after using chmod +x as stated in the documentation

**Led device name**
Respeaker 4

**The bug**
When the installer is used using sudo permissions as stated in the documentation it fails to create the configuration file.

**Debug output**
sed: can’t read /home/pi/.config/hermesLedControl/configuration.yml

**To Reproduce**
Raspberry pi4 with respeaker 4

sudo chmod +x hlc_download.sh
sudo ./hlc_download.sh

**Comment by jazzy-r** [comment]
https://community.rhasspy.org/t/hermesledcontrol-cannot-create-configuration-yml-file/2279

Added how I resolved this here.

**Comment by Psychokiller1888** [comment]
@Xenira This seems to be linked to your recent changes adding a config yaml?

**Comment by Xenira** [comment]
Ill have a look

**Comment by Xenira** [comment]
Sorry about that. The config directory was already present while testing.
Added the missing mkdir.
