### ISSUE TITLE
Add new config file information to Wiki

### ISSUE THREAD

**Issue by Xenira** [project-alice-assistant/HermesLedControl#96]
**Is your feature request related to a problem? Please describe.**
The configuration file information needs to be added to the wiki.

**Describe the solution you'd like**
The 'Arguments customization' page needs to be updated with information about the config file.

**Describe alternatives you've considered**
None

**Additional context**
I would add the information but contributing to wiki projects seems complicated on github.

**Comment by Psychokiller1888** [comment]
Hi!

You can clone the wiki locally: https://puu.sh/HdQeE.png

Then it's like any GH contrib :) Thanks for your work!
