### ISSUE TITLE
Rename 4-mic array in the script

### ISSUE THREAD

**Issue by Pittermaennchen** [project-alice-assistant/HermesLedControl#98]
**My misunderstanding**
I´m right now trying to install the Respeaker 4-Mic Array on my Raspberry Pi 3. When running the LED-control-script, I don't understand which microphone name I should choose. 

**Describe the solution you'd like**
Is "Respeaker 4" the Respeaker 4-Mic Array? Then it would be better to change the name to "Respeaker 4-Mic Array". This way it would be easier to understand for noobs like me.

**Describe alternatives you've considered**
If "Respeaker 4" is not the same as the 4-Mic Array, then I would love support for the 4-Mic-Array

Thank you! Great work by the way!

**Comment by Psychokiller1888** [comment]
Yes, respeaker 4 is this one: https://wiki.seeedstudio.com/ReSpeaker_4_Mic_Array_for_Raspberry_Pi/
